name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Generate deviceBreakpoints.less
        run: node scripts/generate-less.js

      - name: Build project
        run: npm run build
